services:
  db-proyectos:
    image: postgres:15-alpine
    container_name: postgres_innovatech
    networks:
      - innovatech-net
    environment:
      - POSTGRES_DB=gestion_proyectos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always # <--- AGREGAR ESTO

  api-proyectos:
    build:
      context: ./api-proyectos
    container_name: api_proyectos
    restart: on-failure # <--- AGREGAR ESTO (Clave para el reintento)
    ports:
      - "8084:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-proyectos:5432/gestion_proyectos
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
    networks:
      - innovatech-net
    depends_on:
      - db-proyectos

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api_gateway
    ports:
      - "8085:8083" # Puerto 8085 en tu PC -> Puerto 8083 dentro del contenedor
    networks:
      - innovatech-net
    depends_on:
      - api-proyectos
   

networks:
  innovatech-net:
    driver: bridge
